apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: "kubdemotest"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "kubdemotest"
    spec:
      containers:
        - name: "kubdemotest"
          image: "andrenewtest.azurecr.io/kubdemotest"
          ports:
          - containerPort: 443