apiVersion: v1
kind: Service
metadata:
    name: "kubdemotest"
    labels:
        app: "kubdemotest"
spec:
    type: LoadBalancer
    ports:
    - port: 443
      targetPort: http
      protocol: TCP
      name: http
    selector:
        app: "kubdemotest"